### ISSUE TITLE
Certificate validation error

### ISSUE THREAD

**Issue by tehniemer** [earthybeet/readarr-metadata-scraper#1]
I'm not sure if you're still working on this project, but I'm getting a certificate validation error, here's the log. Any help would be greatly appreciated.

```
2024-08-29 07:24:38.1|Error|X509CertificateValidationService|Certificate validation for api.bookinfo.club failed. RemoteCertificateChainErrors
2024-08-29 07:24:38.1|Error|RefreshAuthorService|Couldn't refresh info for [76671][Kyle Mills]

[v0.3.32.2587] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 116
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Readarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 327
   at NzbDrone.Core.Http.CachedHttpResponseService.Get(HttpRequest request, Boolean useCache, TimeSpan ttl) in ./Readarr.Core/Http/CachedHttpResponseService.cs:line 40
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 618
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.<>c__DisplayClass30_0.<PollAuthor>b__0() in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 592
   at LazyCache.AppCacheExtensions.<>c__DisplayClass7_0`1.<GetOrAdd>b__0(ICacheEntry _)
   at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at LazyCache.AppCacheExtensions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory, MemoryCacheEntryOptions policy)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthor(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 591
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 99
   at NzbDrone.Core.Books.RefreshAuthorService.GetSkyhookData(String foreignId) in ./Readarr.Core/Books/Services/RefreshAuthorService.cs:line 91
   at NzbDrone.Core.Books.RefreshAuthorService.RefreshSelectedAuthors(List`1 authorIds, Boolean isNew, CommandTrigger trigger) in ./Readarr.Core/Books/Services/RefreshAuthorService.cs:line 350
```

**Comment by Je11yBe4n** [comment]
Im having the same issue. I think we may need an updated bookinfo-club.crt?

**Comment by jkoestner** [comment]
you could do something like this

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /pathto/certs/bookinfo-club.key -out /pathto/certs/bookinfo-club.crt -subj "/CN=api.bookinfo.club"
```

however i don't think it does well at all the calls that readarr makes such as updating an author. i currently get around this though by running the container for metadata when i want to add a new book and then turning it off afterwards. if readarr catches up to goodreads this wouldn't be a problem for me.

**Comment by blampe** [comment]
For @tehniemer @Je11yBe4n @jkoestner and anyone else who comes across this, take a look at http://github.com/blampe/rreading-glasses for another alternative metadata server. There's a hosted instance available at `https://api.bookinfo.pro/` which can be configured on the hidden `/settings/development` page, or you can self-host.
